require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Documentation:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
Rails/I18nLocaleTexts:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
Metrics/MethodLength:
  Max: 30
RSpec/MultipleMemoizedHelpers:
  Enabled: false


AllCops:
  NewCops: enable
  Exclude:
    - "db/schema*.rb"
    - "node_modules/**/*"
    - "db/migrate/**/*"
    - "config/**/*"
    - "bin/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "log/**/*"
  
