require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec

Style/FrozenStringLiteralComment:
  Enabled: false
Layout/EndOfLine:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Documentation:
  Enabled: false
AllCops:
  NewCops: enable
  Exclude:
    - "db/schema*.rb"
    - "node_modules/**/*"
    - "db/migrate/**/*"
    - "config/**/*"
    - "bin/**/*"
    - "public/**/*"
    - "tmp/**/*"
    - "log/**/*"
  
