version: '3'
services:
  db:
    container_name: wwwsite-db
    image: mysql:8.0.35
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - 3306:3306
    volumes:
      - mysql_db_volume:/var/lib/mysql

  app:
    container_name: wwwsite-app
    build: .
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      SELENIUM_DRIVER_URL: http://selenium_chrome:4444/wd/hub
    volumes:
      - .:/app
      - ~/.ssh/fpb-wwwsite_conoha:/root/.ssh/fpb-wwwsite_conoha
      - rails_gem_volume:/usr/local/bundle
    ports:
      - 8000:3000
    depends_on:
      - db
  
  browser:
    container_name: wwwsite-browser
    image: selenium/standalone-chrome-debug
  


volumes:
  mysql_db_volume:
  rails_gem_volume:
